databases:
  - name: schedulite-db
    plan: free
    databaseName: schedulite
    user: schedulite

services:
  - type: web
    name: schedulite
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    preDeployCommand: bundle exec rails db:migrate
    healthCheckPath: /health
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: LOCKBOX_MASTER_KEY
        sync: false
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: APP_HOST
        value: https://www.schedulite.io
      - key: DATABASE_URL
        fromDatabase:
          name: schedulite-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: schedulite-redis
          type: redis
          property: connectionString

  - type: worker
    name: schedulite-worker
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: bundle exec sidekiq -C config/sidekiq.yml
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: LOCKBOX_MASTER_KEY
        sync: false
      - key: SECRET_KEY_BASE
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: schedulite-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: schedulite-redis
          type: redis
          property: connectionString

  - type: redis
    name: schedulite-redis
    plan: free
    maxmemoryPolicy: noeviction
