name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Scan for security vulnerabilities
        run: bundle exec brakeman --no-pager

      - name: Scan for known gem vulnerabilities
        run: bundle exec bundler-audit check

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Lint code for consistent style
        run: bundle exec rubocop

  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      LOCKBOX_MASTER_KEY: "0000000000000000000000000000000000000000000000000000000000000001"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install npm dependencies
        run: npm install

      - name: Build assets
        run: npm run build && npm run build:css

      - name: Set up database
        run: bundle exec rails db:create db:migrate

      - name: Run RSpec
        run: bundle exec rspec --format documentation

      - name: Run Brakeman
        run: bundle exec brakeman -q --no-pager
